debug: false # ?? ???? ?? ??? ???? ?
management.endpoints.web.exposure.include: "*" # Spring Boot Actuator Endpoints ? ????? ????? ???? ??

logging:
  level:
    com.tdf.community: debug # community ????? ??? ??
    org.springframework.web.servlet: debug # ?? debug ??? ? ?? Request, Response ??? ?
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA? ?? ??? ?? -> ????? ?? ???? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 66356635
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true # Test ? ??????? ??? ? ??? ?? (??? ??)
    hibernate.ddl-auto: create # Entity? ???? ???? ddl?? ???? ???
    show-sql: true # sql debug
    properties:
      hibernate:
        format_sql: true # ??? ??? ????? ??? ?? ???
        default_batch_fetch_size: 100 # JPA?? ??? ????? ???????? ??? ??? ???? ?? ??
#  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
  data:
    rest:
      detection-strategy: annotated
